global:
  domain: ""
  limitsEnabled: true
  dataPartitionId: "osdu"

data:
  #Deployment
  requestsCpu: "5m"
  requestsMemory: "350Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""
  #Configmap
  logLevel: "ERROR"
  entitlementsHost: "http://entitlements"
  partitionHost: "http://partition"
  storageHost: "http://storage"

conf:
  configmap: "file-config"
  appName: "file"
  rabbitmqSecretName: "rabbitmq-secret"
  s3SecretName: "file-seaweedfs-secret"
  fileKeycloakSecretName: "file-keycloak-secret"
  filePostgresSecretName: "file-postgres-secret"
  replicas: 1

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "512Mi"
  sidecarInject: true
