package org.opengroup.osdu.file.model.filemetadata;

import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import io.swagger.v3.oas.annotations.media.Schema;
import org.opengroup.osdu.core.common.model.entitlements.Acl;
import org.opengroup.osdu.core.common.model.entitlements.validation.ValidAcl;
import org.opengroup.osdu.core.common.model.legal.Legal;
import org.opengroup.osdu.core.common.model.storage.validation.ValidKind;
import org.opengroup.osdu.file.model.filemetadata.filedetails.FileData;
import org.opengroup.osdu.file.model.storage.Ancestry;
import org.opengroup.osdu.file.validation.filemetadata.BusinessRuleValidation;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
@Schema(description = "Metadata record")
public class RecordVersion {

    @Schema(description = "Unique identifier generated by the system for the file metadata record.")
    private String id;

    @Schema(description = "Kind of data being ingested. Must follow the naming\n" +
      "  convention:data-Partition-Id}:dataset-name}:record-type}:version}.", example = "osdu:wks:dataset--File.Generic:1.0.0")
    @Valid
    @NotNull(message = "kind must not be null")
    @ValidKind(groups = BusinessRuleValidation.class)
    private String kind;


    @NotNull(message = "acl must not be null")
    @ValidAcl(groups = BusinessRuleValidation.class)
    @JsonProperty("acl")
    private Acl acl;

    @Valid
    @NotNull(message = "legal tag cannot be empty")
    private Legal legal;

    @Valid
    @NotNull(message = "data cannot be empty")
    private FileData data;

    private Ancestry ancestry;

    @Schema(description = "The version number of this OSDU resource; set by the framework." , example = "1831253916104085")
    private Long version;

    private List<Map<String, Object>> meta;

    private Map<String, String> tags;


}
